//! Does `#[guarded_body]` actually contain a panic that would otherwise abort?
//!
//! This is the test that matters for the "must not panic" issue. It builds two
//! bodies into one extension:
//!
//!   * `guarded_panicking_body` — generated by the macro
//!   * `raw_panicking_body`     — hand-written `extern "C"`, the old way
//!
//! Both panic. The first must return `KWABI_ERR_PANICKED`; the second must
//! abort. If the first aborts, the macro does not work and the whole approach
//! is wrong.
//!
//! Built as a cdylib so it has its own Rust std — the same topology as a real
//! kwabi extension, and the topology in which the runtime's `catch_unwind`
//! fails. That detail is the point: a test that linked everything into one
//! image would pass without proving anything.

use kwabi::guarded_body;
use std::os::raw::c_void;

/// Arguments the caller passes through `kwabi_try`'s `arg` pointer.
#[repr(C)]
pub struct PanicArgs {
    pub should_panic: i32,
}

/// A body that panics when asked. The macro wraps it, so the panic is caught
/// by this crate's own std and turned into a status.
#[guarded_body]
fn guarded_maybe_panics(args: &mut PanicArgs) -> Result<(), String> {
    if args.should_panic != 0 {
        panic!("guarded: deliberate panic, should be contained");
    }
    Ok(())
}

/// A body that panics, hand-written the old way: no guard inside this crate.
///
/// This is what the contract forbids and what used to abort the postmaster.
/// Kept so the difference is demonstrable rather than asserted.
#[no_mangle]
pub extern "C" fn raw_panicking_body(_arg: *mut c_void) -> i32 {
    panic!("raw: deliberate panic, expected to abort");
}

/// A body that reports a failure without panicking, via `Result`.
#[guarded_body]
fn guarded_reports_failure(args: &mut PanicArgs) -> Result<(), String> {
    if args.should_panic != 0 {
        return Err("guarded: reported failure, not a panic".to_string());
    }
    Ok(())
}

/// A body that succeeds.
#[guarded_body]
fn guarded_succeeds(_args: &mut PanicArgs) -> Result<(), String> {
    Ok(())
}

/// Read back the message the macro stored for the last contained failure.
#[no_mangle]
pub extern "C" fn guarded_last_error_len() -> i32 {
    kwabi::guarded::last_error().map(|s| s.len() as i32).unwrap_or(-1)
}
