//! Does `#[guarded_body]` actually contain a panic that would otherwise abort?
//!
//! This is the test that matters for the "must not panic" issue. It builds two
//! bodies into one extension:
//!
//!   * `guarded_panicking_body` — generated by the macro
//!   * `raw_panicking_body`     — hand-written `extern "C"`, the old way
//!
//! Both panic. The first must return `KWABI_ERR_PANICKED`; the second must
//! abort. If the first aborts, the macro does not work and the whole approach
//! is wrong.
//!
//! Built as a cdylib so it has its own Rust std — the same topology as a real
//! kwabi extension, and the topology in which the runtime's `catch_unwind`
//! fails. That detail is the point: a test that linked everything into one
//! image would pass without proving anything.

use kwabi::{guarded_body, require_unwind};

// The crate-level check: for extensions that hand-write trampolines.
require_unwind!();
use std::os::raw::c_void;

/// Arguments the caller passes through `kwabi_try`'s `arg` pointer.
#[repr(C)]
pub struct PanicArgs {
    pub should_panic: i32,
}

/// A body that panics when asked. The macro wraps it, so the panic is caught
/// by this crate's own std and turned into a status.
#[guarded_body]
fn guarded_maybe_panics(args: &mut PanicArgs) -> Result<(), String> {
    if args.should_panic != 0 {
        panic!("guarded: deliberate panic, should be contained");
    }
    Ok(())
}

/// A body that panics, hand-written the old way: no guard inside this crate.
///
/// This is what the contract forbids and what used to abort the postmaster.
/// Kept so the difference is demonstrable rather than asserted.
#[no_mangle]
pub extern "C" fn raw_panicking_body(_arg: *mut c_void) -> i32 {
    panic!("raw: deliberate panic, expected to abort");
}

/// A body that reports a failure without panicking, via `Result`.
#[guarded_body]
fn guarded_reports_failure(args: &mut PanicArgs) -> Result<(), String> {
    if args.should_panic != 0 {
        return Err("guarded: reported failure, not a panic".to_string());
    }
    Ok(())
}

/// A body that succeeds.
#[guarded_body]
fn guarded_succeeds(_args: &mut PanicArgs) -> Result<(), String> {
    Ok(())
}

/// Read back the message the macro stored for the last contained failure.
#[no_mangle]
pub extern "C" fn guarded_last_error_len() -> i32 {
    kwabi::guarded::last_error().map(|s| s.len() as i32).unwrap_or(-1)
}


/// A body that reports a fully structured error.
///
/// This is the DX payoff in one function: the caller receives a SQLSTATE it can
/// match on, a message, a detail line, a hint, and the offending column name --
/// all as separate fields, with no prose parsing.
#[guarded_body]
fn guarded_reports_structured(args: &mut PanicArgs) -> Result<(), kwabi::guarded::KwabiReport> {
    use kwabi::guarded::KwabiReport;
    if args.should_panic != 0 {
        return Err(
            KwabiReport::new("22023", "value out of range")
                .detail("Allowed range is 1 to 100.")
                .hint("Check the extension's configuration.")
                .column("amount")
                .table("invoices")
        );
    }
    Ok(())
}

// ========================================================================
// The capability bitset, consumed
// ========================================================================

/// Arguments for the capability-gated body.
///
/// `i32` because that is the width this harness passes through
/// `kwabi_try_symbol`'s argument buffer. `arg` is opaque to the ABI -- each
/// extension chooses its own type -- so this is a property of the harness,
/// not of the ABI.
#[repr(C)]
pub struct CapArgs {
    /// Mask of `KWABI_CAP_*` bits the body requires before it will run.
    pub required: i32,
}

/// A body that refuses to run unless the runtime GUARANTEES what it needs.
///
/// This is the first real consumer of the capability bitset. The bitset
/// existed, was derived from the table, and was proven behaviourally -- but
/// until now nothing *branched* on it, so the question "does a bit actually
/// control behaviour?" was untested at the point extensions would ask it.
///
/// The motivating case is an extension that WRITES, and it is why the answer
/// cannot come from a slot test. A non-NULL `try_body` says the runtime can
/// contain an error. It says nothing about whether the failed body's partial
/// writes were rolled back. Only `ATOMIC_BODY` says that, and an extension
/// that writes must not proceed without it -- catching an ERROR without a
/// subtransaction is *worse* than not catching it, because the caller believes
/// the operation failed while it partially succeeded.
///
/// So the body asks the narrower question and refuses cleanly when the answer
/// is no, rather than relying on a promise the runtime never made.
#[guarded_body]
fn guarded_requires_capability(args: &mut CapArgs) -> Result<(), kwabi::guarded::KwabiReport> {
    use kwabi::guarded::KwabiReport;

    // No table means kwabi_ext_init was never called, which is a caller bug
    // rather than a runtime limitation, so it is reported separately.
    let Some(api) = kwabi::instance() else {
        return Err(
            KwabiReport::new("0A000", "kwabi: the extension was not initialised")
                .detail("kwabi_ext_init has not been called, so there is no function table.")
                .hint("Load the extension through kwabi_load_extension before calling its bodies.")
        );
    };

    // pg_major is unused when the slot is present; the SDK applies the
    // bootstrap rule, so a NULL slot yields CORE-only rather than zero.
    let caps = api.capabilities(0);
    let required = args.required as u64;
    let missing = required & !caps.0;

    if missing != 0 {
        return Err(
            KwabiReport::new("0A000", "kwabi: runtime does not guarantee a required capability")
                .detail(&format!(
                    "required={:#x} missing={:#x}; runtime claims: {}",
                    required,
                    missing,
                    caps.names()
                ))
                .hint(
                    "Refusing rather than proceeding: relying on an unguaranteed promise \
                     is how an extension gets silent inconsistency instead of an error.",
                )
        );
    }

    Ok(())
}

/// Report what this runtime claims, read through the SDK accessor.
///
/// Proves the consumer path end to end: the body reaches the table through
/// `kwabi::instance()`, and the answer arrives as capability *names* rather
/// than a raw integer. If the SDK's table were short a slot, or the bootstrap
/// rule were applied wrongly, this returns the wrong list.
#[no_mangle]
pub extern "C" fn guarded_capability_names() -> *mut std::os::raw::c_char {
    use std::os::raw::c_char;
    let text = match kwabi::instance() {
        Some(api) => api.capabilities(0).names(),
        None => "(no table: kwabi_ext_init not called)".to_string(),
    };
    // Leaked deliberately: this is a test helper whose result is read
    // immediately by the caller, and freeing across the ABI would need a
    // second slot to do it.
    std::ffi::CString::new(text)
        .map(|c| c.into_raw() as *mut c_char)
        .unwrap_or(std::ptr::null_mut())
}
