// @generated by gen_kwabi_struct.py from kwabi.h — do not edit by hand.
//
// The layout of this struct IS the ABI. Field order must match kwabi.h
// exactly; the harness asserts on size_of::<KwabiV1>() so drift fails a
// test rather than corrupting memory in production.

use std::os::raw::{c_char, c_int, c_long, c_void};

// ---- capabilities (mirrors kwabi.h) ----

/// A capability bit says what a runtime GUARANTEES, not which slots
/// exist. A NULL slot cannot express "implemented, but with a weaker
/// guarantee than you need"; these bits can. See kwabi.h.
///
/// Hard rule: a bit MUST NOT be derivable from a slot test. If testing a
/// slot gives the same answer, the bit is noise.
pub const KWABI_CAP_CORE: u64 = 1 << 0;
pub const KWABI_CAP_STRUCTURED_ERRORS: u64 = 1 << 1;
pub const KWABI_CAP_ERROR_FIREWALL: u64 = 1 << 2;
pub const KWABI_CAP_MEMORY_INTROSPECTION: u64 = 1 << 3;
pub const KWABI_CAP_ATOMIC_BODY: u64 = 1 << 4;
pub const KWABI_CAP_ALL: u64 = KWABI_CAP_CORE
    | KWABI_CAP_STRUCTURED_ERRORS
    | KWABI_CAP_ERROR_FIREWALL
    | KWABI_CAP_MEMORY_INTROSPECTION
    | KWABI_CAP_ATOMIC_BODY;

/// Stable ABI version published by this runtime.
pub const KWABI_VERSION: u32 = 1;

// ---- error firewall types (mirrors kwabi.h) ----

/// Status codes. `KWABI_OK` is 0 so an integer check reads naturally.
pub const KWABI_OK: c_int = 0;
pub const KWABI_ERR_RAISED: c_int = 1;
pub const KWABI_ERR_PANICKED: c_int = 2;
pub const KWABI_ERR_BODY_RAISED: c_int = 3;
pub const KWABI_ERR_BAD_ARG: c_int = 4;

/// Field sizes. Must match the KWABI_ERR*_MAX defines in kwabi.h.
pub const KWABI_ERRMSG_MAX: usize = 512;
pub const KWABI_ERRDETAIL_MAX: usize = 512;
pub const KWABI_ERRHINT_MAX: usize = 384;
pub const KWABI_ERRNAME_MAX: usize = 128;

/// Smallest `KwabiError` that can carry the extended fields.
///
/// The capability bit for structured errors is set only when the struct
/// we compiled against is at least this large, so the bit cannot be
/// claimed by a build whose struct has no detail/hint/object fields.
pub const KWABI_ERR_STRUCTURED_MIN: usize =
    4 + 4 + 4 + KWABI_ERRMSG_MAX + KWABI_ERRDETAIL_MAX + KWABI_ERRHINT_MAX + 5 * KWABI_ERRNAME_MAX;

/// The structured error channel.
///
/// `size` is first and must stay first: it is what lets a writer built
/// against a newer header refuse to write past a caller's older, smaller
/// struct. See the long comment in kwabi.h for why that case is the normal
/// one rather than an edge case.
///
/// All strings are fixed arrays, so the struct has no ownership question:
/// it crosses by value and can be copied or zeroed freely.
#[repr(C)]
pub struct KwabiError {
    pub size: u32,
    pub sqlerrcode: c_int,
    pub status: c_int,
    pub message: [c_char; KWABI_ERRMSG_MAX],
    pub detail: [c_char; KWABI_ERRDETAIL_MAX],
    pub hint: [c_char; KWABI_ERRHINT_MAX],
    pub schema_name: [c_char; KWABI_ERRNAME_MAX],
    pub table_name: [c_char; KWABI_ERRNAME_MAX],
    pub column_name: [c_char; KWABI_ERRNAME_MAX],
    pub datatype_name: [c_char; KWABI_ERRNAME_MAX],
    pub constraint_name: [c_char; KWABI_ERRNAME_MAX],
}

impl KwabiError {
    /// Offset of a field, for the size guards the writer uses.
    pub fn new() -> Self {
        Self::default()
    }
}

impl Default for KwabiError {
    fn default() -> Self {
        KwabiError {
            size: std::mem::size_of::<KwabiError>() as u32,
            sqlerrcode: 0,
            status: KWABI_OK,
            message: [0; KWABI_ERRMSG_MAX],
            detail: [0; KWABI_ERRDETAIL_MAX],
            hint: [0; KWABI_ERRHINT_MAX],
            schema_name: [0; KWABI_ERRNAME_MAX],
            table_name: [0; KWABI_ERRNAME_MAX],
            column_name: [0; KWABI_ERRNAME_MAX],
            datatype_name: [0; KWABI_ERRNAME_MAX],
            constraint_name: [0; KWABI_ERRNAME_MAX],
        }
    }
}

/// A guarded body. Must not raise, and must not panic.
///
/// `extern "C"`, deliberately. A panic escaping it aborts the process at
/// the body's own boundary, which is the body's bug and is caught during
/// development. `C-unwind` was tried and is WORSE: it lets the panic
/// travel into the runtime's catch_unwind, where -- if the body came from
/// a separately built extension with its own Rust std -- it is a *foreign
/// exception* and aborts anyway, with a much less useful message. See
/// notes/error-firewall-design.md section 4.
/// A guarded body. Must not raise, and must not panic.
///
/// The second parameter is the caller's error channel: it is how a body
/// reports a STRUCTURED error rather than only a status. Added after the
/// first prototype, where `(void *arg)` alone left the body with no way
/// to reach the channel at all.
pub type KwabiBodyFn = unsafe extern "C" fn(*mut c_void, *mut KwabiError) -> c_int;

#[repr(C)]
pub struct KwabiV1 {
    pub version: u32,
    pub fmgr_info: Option<unsafe extern "C" fn(u32) -> *mut c_void>,
    pub call_function: Option<
        unsafe extern "C" fn(
            *mut c_void,
            c_int,
            *mut usize,
            *const bool,
            *mut bool,
            *mut usize,
        ) -> c_int,
    >,
    pub call_function1:
        Option<unsafe extern "C" fn(*mut c_void, usize, *mut bool, *mut usize) -> c_int>,
    pub call_function2:
        Option<unsafe extern "C" fn(*mut c_void, usize, usize, *mut bool, *mut usize) -> c_int>,
    pub call_function3: Option<
        unsafe extern "C" fn(*mut c_void, usize, usize, usize, *mut bool, *mut usize) -> c_int,
    >,
    pub spi_execute: Option<unsafe extern "C" fn(*const c_char, bool, c_int) -> *mut c_void>,
    pub spi_execute_plan: Option<
        unsafe extern "C" fn(*mut c_void, *mut usize, *const c_char, bool, c_int) -> *mut c_void,
    >,
    pub spi_free_result: Option<unsafe extern "C" fn(*mut c_void) -> ()>,
    pub spi_result_ntuples: Option<unsafe extern "C" fn(*mut c_void) -> c_int>,
    pub spi_result_get_value: Option<unsafe extern "C" fn(*mut c_void, c_int, c_int) -> usize>,
    pub type_input: Option<unsafe extern "C" fn(u32, *const c_char, i32) -> usize>,
    pub type_output: Option<unsafe extern "C" fn(u32, usize) -> *mut c_char>,
    pub type_recv: Option<unsafe extern "C" fn(u32, *mut c_void) -> usize>,
    pub type_send: Option<unsafe extern "C" fn(u32, usize, *mut c_void) -> ()>,
    pub type_element_type: Option<unsafe extern "C" fn(u32) -> u32>,
    pub type_length: Option<unsafe extern "C" fn(u32) -> i16>,
    pub type_is_array: Option<unsafe extern "C" fn(u32) -> bool>,
    pub type_is_composite: Option<unsafe extern "C" fn(u32) -> bool>,
    pub type_base_type: Option<unsafe extern "C" fn(u32) -> u32>,
    pub parse_expr: Option<unsafe extern "C" fn(*const c_char, *mut u32, c_int) -> *mut c_void>,
    pub parse_stmt: Option<unsafe extern "C" fn(*const c_char) -> *mut c_void>,
    pub parse_type: Option<unsafe extern "C" fn(*const c_char) -> *mut c_void>,
    pub free_node: Option<unsafe extern "C" fn(*mut c_void) -> ()>,
    pub oper_left_type: Option<unsafe extern "C" fn(u32) -> u32>,
    pub oper_right_type: Option<unsafe extern "C" fn(u32) -> u32>,
    pub oper_result_type: Option<unsafe extern "C" fn(u32) -> u32>,
    pub oper_is_commutative: Option<unsafe extern "C" fn(u32) -> bool>,
    pub extension_oid: Option<unsafe extern "C" fn(*const c_char) -> u32>,
    pub extension_installed: Option<unsafe extern "C" fn(*const c_char) -> bool>,
    pub extension_version: Option<unsafe extern "C" fn(*const c_char) -> *const c_char>,
    pub sequence_nextval: Option<unsafe extern "C" fn(u32) -> i64>,
    pub sequence_currval: Option<unsafe extern "C" fn(u32) -> i64>,
    pub sequence_setval: Option<unsafe extern "C" fn(u32, i64) -> i64>,
    pub logical_decoding_begin: Option<unsafe extern "C" fn(u32, i64) -> *mut c_void>,
    pub logical_decoding_end: Option<unsafe extern "C" fn(*mut c_void) -> ()>,
    pub logical_decoding_read:
        Option<unsafe extern "C" fn(*mut c_void, *mut i64, *mut c_void) -> bool>,
    pub output_plugin_startup: Option<unsafe extern "C" fn(*mut c_void) -> ()>,
    pub output_plugin_shutdown: Option<unsafe extern "C" fn(*mut c_void) -> ()>,
    pub bgworker_register:
        Option<unsafe extern "C" fn(*const c_char, *mut c_void, *mut c_void) -> u32>,
    pub bgworker_terminate: Option<unsafe extern "C" fn(u32) -> ()>,
    pub bgworker_is_running: Option<unsafe extern "C" fn(u32) -> bool>,
    pub block_get_number: Option<unsafe extern "C" fn(*mut c_void) -> u32>,
    pub block_get_offset: Option<unsafe extern "C" fn(*mut c_void) -> u16>,
    pub block_is_valid: Option<unsafe extern "C" fn(*mut c_void) -> bool>,
    pub slru_create: Option<unsafe extern "C" fn(*const c_char, c_int, c_int) -> ()>,
    pub slru_read: Option<unsafe extern "C" fn(*const c_char, i64, *mut c_void) -> ()>,
    pub slru_write: Option<unsafe extern "C" fn(*const c_char, i64, *const c_void) -> ()>,
    pub value_is_null: Option<unsafe extern "C" fn(*mut c_void) -> bool>,
    pub value_get_datum: Option<unsafe extern "C" fn(*mut c_void) -> usize>,
    pub value_get_type: Option<unsafe extern "C" fn(*mut c_void) -> u32>,
    pub value_get_typmod: Option<unsafe extern "C" fn(*mut c_void) -> i32>,
    pub palloc: Option<unsafe extern "C" fn(usize) -> *mut c_void>,
    pub palloc0: Option<unsafe extern "C" fn(usize) -> *mut c_void>,
    pub repalloc: Option<unsafe extern "C" fn(*mut c_void, usize) -> *mut c_void>,
    pub pfree: Option<unsafe extern "C" fn(*mut c_void) -> ()>,
    pub memory_context_current: Option<unsafe extern "C" fn() -> *mut c_void>,
    pub memory_context_switch_to: Option<unsafe extern "C" fn(*mut c_void) -> *mut c_void>,
    pub memory_context_reset: Option<unsafe extern "C" fn(*mut c_void) -> ()>,
    pub memory_context_delete: Option<unsafe extern "C" fn(*mut c_void) -> ()>,
    pub ereport: Option<unsafe extern "C" fn(c_int, *const c_char, *const c_char) -> ()>,
    pub elog: Option<unsafe extern "C" fn(c_int, *const c_char, *const c_char) -> ()>,
    pub error_message: Option<unsafe extern "C" fn() -> *const c_char>,
    pub error_code: Option<unsafe extern "C" fn() -> c_int>,
    pub error_clear: Option<unsafe extern "C" fn() -> ()>,
    pub relation_open: Option<unsafe extern "C" fn(u32, u32) -> *mut c_void>,
    pub relation_close: Option<unsafe extern "C" fn(*mut c_void, u32) -> ()>,
    pub relation_id: Option<unsafe extern "C" fn(*mut c_void) -> u32>,
    pub relation_name: Option<unsafe extern "C" fn(*mut c_void) -> *const c_char>,
    pub relation_namespace: Option<unsafe extern "C" fn(*mut c_void) -> u32>,
    pub relation_tupledesc: Option<unsafe extern "C" fn(*mut c_void) -> *mut c_void>,
    pub syscache_get_oid: Option<unsafe extern "C" fn(*const c_char, *const c_char, usize) -> u32>,
    pub syscache_get_tuple: Option<unsafe extern "C" fn(*const c_char, usize) -> *mut c_void>,
    pub syscache_free_tuple: Option<unsafe extern "C" fn(*mut c_void) -> ()>,
    pub planner_info: Option<unsafe extern "C" fn(*mut c_void, c_int, *mut c_void) -> *mut c_void>,
    pub free_planner_info: Option<unsafe extern "C" fn(*mut c_void) -> ()>,
    pub planner_estimate_rows: Option<unsafe extern "C" fn(*mut c_void, *mut c_void) -> f64>,
    pub planner_estimate_cost: Option<unsafe extern "C" fn(*mut c_void, *mut c_void) -> f64>,
    pub transaction_start: Option<unsafe extern "C" fn() -> ()>,
    pub transaction_commit: Option<unsafe extern "C" fn() -> ()>,
    pub transaction_abort: Option<unsafe extern "C" fn() -> ()>,
    pub transaction_is_active: Option<unsafe extern "C" fn() -> bool>,
    pub transaction_get_current_xid: Option<unsafe extern "C" fn() -> i64>,
    pub shmem_alloc: Option<unsafe extern "C" fn(usize) -> *mut c_void>,
    pub shmem_free: Option<unsafe extern "C" fn(*mut c_void) -> ()>,
    pub shmem_get: Option<unsafe extern "C" fn(*const c_char, usize) -> *mut c_void>,
    pub lock_acquire: Option<unsafe extern "C" fn(*mut c_void, u32) -> ()>,
    pub lock_release: Option<unsafe extern "C" fn(*mut c_void) -> ()>,
    pub lock_held_by_me: Option<unsafe extern "C" fn(*mut c_void) -> bool>,
    pub spin_acquire: Option<unsafe extern "C" fn(*mut c_void) -> ()>,
    pub spin_release: Option<unsafe extern "C" fn(*mut c_void) -> ()>,
    pub autovacuum_is_running: Option<unsafe extern "C" fn() -> bool>,
    pub autovacuum_naptime: Option<unsafe extern "C" fn() -> c_int>,
    pub syslogger_log: Option<unsafe extern "C" fn(*const c_char) -> ()>,
    pub walsender_send: Option<unsafe extern "C" fn(*const c_char, c_int) -> ()>,
    pub walsender_receive: Option<unsafe extern "C" fn(*mut c_char, c_int) -> c_int>,
    pub walsender_is_connected: Option<unsafe extern "C" fn() -> bool>,
    pub defrem_create:
        Option<unsafe extern "C" fn(*const c_char, *const c_char, *const c_char) -> ()>,
    pub defrem_alter: Option<unsafe extern "C" fn(*const c_char, *const c_char) -> ()>,
    pub defrem_drop: Option<unsafe extern "C" fn(*const c_char) -> ()>,
    pub node_type: Option<unsafe extern "C" fn(*mut c_void) -> u32>,
    pub node_type_name: Option<unsafe extern "C" fn(*mut c_void) -> *const c_char>,
    pub node_get_list: Option<unsafe extern "C" fn(*mut c_void) -> *mut c_void>,
    pub node_list_length: Option<unsafe extern "C" fn(*mut c_void) -> c_int>,
    pub node_list_get: Option<unsafe extern "C" fn(*mut c_void, c_int) -> *mut c_void>,
    pub query_command_type: Option<unsafe extern "C" fn(*mut c_void) -> u32>,
    pub query_rtable: Option<unsafe extern "C" fn(*mut c_void) -> *mut c_void>,
    pub query_target_list: Option<unsafe extern "C" fn(*mut c_void) -> *mut c_void>,
    pub query_returning_list: Option<unsafe extern "C" fn(*mut c_void) -> *mut c_void>,
    pub query_jointree: Option<unsafe extern "C" fn(*mut c_void) -> *mut c_void>,
    pub query_group_clause: Option<unsafe extern "C" fn(*mut c_void) -> *mut c_void>,
    pub query_sort_clause: Option<unsafe extern "C" fn(*mut c_void) -> *mut c_void>,
    pub query_limit_offset: Option<unsafe extern "C" fn(*mut c_void) -> *mut c_void>,
    pub query_limit_count: Option<unsafe extern "C" fn(*mut c_void) -> *mut c_void>,
    pub query_has_for_update: Option<unsafe extern "C" fn(*mut c_void) -> bool>,
    pub query_has_row_security: Option<unsafe extern "C" fn(*mut c_void) -> bool>,
    pub planned_stmt_plan_tree: Option<unsafe extern "C" fn(*mut c_void) -> *mut c_void>,
    pub planned_stmt_rtable: Option<unsafe extern "C" fn(*mut c_void) -> *mut c_void>,
    pub planned_stmt_result_relations: Option<unsafe extern "C" fn(*mut c_void) -> *mut c_void>,
    pub planned_stmt_has_returning: Option<unsafe extern "C" fn(*mut c_void) -> bool>,
    pub planned_stmt_has_modifying_cte: Option<unsafe extern "C" fn(*mut c_void) -> bool>,
    pub planned_stmt_is_utility: Option<unsafe extern "C" fn(*mut c_void) -> bool>,
    pub tuple_natts: Option<unsafe extern "C" fn(*mut c_void) -> c_int>,
    pub tuple_typeid: Option<unsafe extern "C" fn(*mut c_void, c_int) -> u32>,
    pub tuple_typmod: Option<unsafe extern "C" fn(*mut c_void, c_int) -> i32>,
    pub tuple_attname: Option<unsafe extern "C" fn(*mut c_void, c_int) -> *const c_char>,
    pub tuple_attisdropped: Option<unsafe extern "C" fn(*mut c_void, c_int) -> bool>,
    pub tuple_attnum: Option<unsafe extern "C" fn(*mut c_void, *const c_char) -> c_int>,
    pub heap_tuple_getattr:
        Option<unsafe extern "C" fn(*mut c_void, c_int, *mut c_void, *mut bool) -> usize>,
    pub heap_tuple_setattr:
        Option<unsafe extern "C" fn(*mut c_void, c_int, usize, *mut c_void) -> *mut c_void>,
    pub heap_tuple_tableoid: Option<unsafe extern "C" fn(*mut c_void) -> u32>,
    pub heap_tuple_tid: Option<unsafe extern "C" fn(*mut c_void) -> *mut c_void>,
    pub slot_isnull: Option<unsafe extern "C" fn(*mut c_void, c_int) -> bool>,
    pub slot_getattr: Option<unsafe extern "C" fn(*mut c_void, c_int, *mut bool) -> usize>,
    pub slot_tupledesc: Option<unsafe extern "C" fn(*mut c_void) -> *mut c_void>,
    pub table_am_get: Option<unsafe extern "C" fn(u32) -> *mut c_void>,
    pub table_am_beginscan:
        Option<unsafe extern "C" fn(*mut c_void, *mut c_void, c_int, *mut c_void) -> *mut c_void>,
    pub table_am_endscan: Option<unsafe extern "C" fn(*mut c_void) -> ()>,
    pub table_am_getnext: Option<unsafe extern "C" fn(*mut c_void, *mut c_void) -> bool>,
    pub table_am_insert:
        Option<unsafe extern "C" fn(*mut c_void, *mut c_void, c_int, *mut c_void) -> ()>,
    pub table_am_update: Option<unsafe extern "C" fn(*mut c_void, *mut c_void, c_int) -> ()>,
    pub table_am_delete: Option<unsafe extern "C" fn(*mut c_void, *mut c_void, c_int) -> ()>,
    pub executor_start: Option<unsafe extern "C" fn(*mut c_void, c_int) -> *mut c_void>,
    pub executor_run: Option<unsafe extern "C" fn(*mut c_void, c_int, c_long, bool) -> ()>,
    pub executor_finish: Option<unsafe extern "C" fn(*mut c_void) -> ()>,
    pub executor_end: Option<unsafe extern "C" fn(*mut c_void) -> ()>,
    pub executor_getnext: Option<unsafe extern "C" fn(*mut c_void) -> *mut c_void>,
    pub buffer_get: Option<unsafe extern "C" fn(*mut c_void, u32) -> *mut c_void>,
    pub buffer_release: Option<unsafe extern "C" fn(*mut c_void) -> ()>,
    pub buffer_get_page: Option<unsafe extern "C" fn(*mut c_void) -> *mut c_void>,
    pub buffer_mark_dirty: Option<unsafe extern "C" fn(*mut c_void) -> ()>,
    pub lwlock_acquire: Option<unsafe extern "C" fn(*mut c_void, u32) -> ()>,
    pub lwlock_release: Option<unsafe extern "C" fn(*mut c_void) -> ()>,
    pub lwlock_held_by_me: Option<unsafe extern "C" fn(*mut c_void) -> bool>,
    pub lwlock_cond_acquire: Option<unsafe extern "C" fn(*mut c_void, u32) -> bool>,
    pub spinlock_acquire: Option<unsafe extern "C" fn(*mut c_void) -> ()>,
    pub spinlock_release: Option<unsafe extern "C" fn(*mut c_void) -> ()>,
    pub spinlock_held_by_me: Option<unsafe extern "C" fn(*mut c_void) -> bool>,
    pub guc_get_int: Option<unsafe extern "C" fn(*const c_char) -> c_int>,
    pub guc_get_string: Option<unsafe extern "C" fn(*const c_char) -> *const c_char>,
    pub guc_get_bool: Option<unsafe extern "C" fn(*const c_char) -> bool>,
    pub guc_get_float: Option<unsafe extern "C" fn(*const c_char) -> f64>,
    pub guc_set_int: Option<unsafe extern "C" fn(*const c_char, c_int) -> ()>,
    pub guc_set_string: Option<unsafe extern "C" fn(*const c_char, *const c_char) -> ()>,
    pub guc_set_bool: Option<unsafe extern "C" fn(*const c_char, bool) -> ()>,
    pub guc_set_float: Option<unsafe extern "C" fn(*const c_char, f64) -> ()>,
    pub explain_query: Option<
        unsafe extern "C" fn(
            *mut c_void,
            *mut c_void,
            *mut c_void,
            *const c_char,
            *mut c_void,
            *mut c_void,
        ) -> (),
    >,
    pub explain_get_index_name: Option<unsafe extern "C" fn(u32) -> *const c_char>,
    pub vacuum_rel: Option<unsafe extern "C" fn(*mut c_void, *mut c_void, *mut c_void) -> ()>,
    pub vacuum_analyze_rel:
        Option<unsafe extern "C" fn(*mut c_void, *mut c_void, *mut c_void) -> ()>,
    pub trigger_desc: Option<unsafe extern "C" fn(*mut c_void) -> *mut c_void>,
    pub trigger_count: Option<unsafe extern "C" fn(*mut c_void) -> c_int>,
    pub trigger_get: Option<unsafe extern "C" fn(*mut c_void, c_int) -> *mut c_void>,
    pub reorderbuffer_get_lsn: Option<unsafe extern "C" fn(*mut c_void) -> i64>,
    pub reorderbuffer_get_xid: Option<unsafe extern "C" fn(*mut c_void, u32) -> i64>,
    pub reorderbuffer_get_changes: Option<unsafe extern "C" fn(*mut c_void, u32) -> c_int>,
    pub slot_get_lsn: Option<unsafe extern "C" fn(u32) -> i64>,
    pub slot_get_catalog_xmin: Option<unsafe extern "C" fn(u32) -> i64>,
    pub slot_is_active: Option<unsafe extern "C" fn(u32) -> bool>,
    pub postmaster_is_alive: Option<unsafe extern "C" fn() -> bool>,
    pub postmaster_get_child_pid: Option<unsafe extern "C" fn(*mut c_void) -> c_int>,
    pub itempointer_get_block_number: Option<unsafe extern "C" fn(*mut c_void) -> u32>,
    pub itempointer_get_offset_number: Option<unsafe extern "C" fn(*mut c_void) -> u16>,
    pub itempointer_is_valid: Option<unsafe extern "C" fn(*mut c_void) -> bool>,
    pub rel_id: Option<unsafe extern "C" fn(*mut c_void) -> u32>,
    pub rel_name: Option<unsafe extern "C" fn(*mut c_void) -> *const c_char>,
    pub rel_namespace: Option<unsafe extern "C" fn(*mut c_void) -> u32>,
    pub rel_relkind: Option<unsafe extern "C" fn(*mut c_void) -> c_char>,
    pub rel_relam: Option<unsafe extern "C" fn(*mut c_void) -> u32>,
    pub rel_tupledesc: Option<unsafe extern "C" fn(*mut c_void) -> *mut c_void>,
    pub rel_index_list: Option<unsafe extern "C" fn(*mut c_void) -> *mut c_void>,
    pub stringinfo_init: Option<unsafe extern "C" fn(*mut c_void) -> ()>,
    pub stringinfo_reset: Option<unsafe extern "C" fn(*mut c_void) -> ()>,
    pub stringinfo_append: Option<unsafe extern "C" fn(*mut c_void, *const c_char) -> ()>,
    pub stringinfo_append_char: Option<unsafe extern "C" fn(*mut c_void, c_char) -> ()>,
    pub stringinfo_append_int: Option<unsafe extern "C" fn(*mut c_void, i64) -> ()>,
    pub stringinfo_data: Option<unsafe extern "C" fn(*mut c_void) -> *const c_char>,
    pub stringinfo_len: Option<unsafe extern "C" fn(*mut c_void) -> c_int>,
    pub memory_chunk_context: Option<unsafe extern "C" fn(*mut c_void) -> *mut c_void>,
    pub current_memory_context: Option<unsafe extern "C" fn() -> *mut c_void>,
    pub raise_error: Option<unsafe extern "C" fn(c_int, *const c_char) -> ()>,
    pub try_body: Option<unsafe extern "C" fn(KwabiBodyFn, *mut c_void, *mut KwabiError) -> c_int>,
    pub error_get: Option<unsafe extern "C" fn(*mut KwabiError) -> ()>,
    pub capabilities: Option<unsafe extern "C" fn() -> u64>,
    pub memory_context_create: Option<unsafe extern "C" fn(*const c_char) -> *mut c_void>,
}

impl KwabiV1 {
    /// Number of fields; asserted against the header by the harness.
    pub const FIELD_COUNT: usize = 205;
}

/// Every slot starts null. An extension MUST test a slot before calling it;
/// a null slot is how this ABI says "this runtime does not implement that
/// yet". Slot presence and capability bits answer different questions -- see
/// the `capabilities` slot and the KWABI_CAP_* constants.
impl Default for KwabiV1 {
    fn default() -> Self {
        KwabiV1 {
            version: KWABI_VERSION,
            fmgr_info: None,
            call_function: None,
            call_function1: None,
            call_function2: None,
            call_function3: None,
            spi_execute: None,
            spi_execute_plan: None,
            spi_free_result: None,
            spi_result_ntuples: None,
            spi_result_get_value: None,
            type_input: None,
            type_output: None,
            type_recv: None,
            type_send: None,
            type_element_type: None,
            type_length: None,
            type_is_array: None,
            type_is_composite: None,
            type_base_type: None,
            parse_expr: None,
            parse_stmt: None,
            parse_type: None,
            free_node: None,
            oper_left_type: None,
            oper_right_type: None,
            oper_result_type: None,
            oper_is_commutative: None,
            extension_oid: None,
            extension_installed: None,
            extension_version: None,
            sequence_nextval: None,
            sequence_currval: None,
            sequence_setval: None,
            logical_decoding_begin: None,
            logical_decoding_end: None,
            logical_decoding_read: None,
            output_plugin_startup: None,
            output_plugin_shutdown: None,
            bgworker_register: None,
            bgworker_terminate: None,
            bgworker_is_running: None,
            block_get_number: None,
            block_get_offset: None,
            block_is_valid: None,
            slru_create: None,
            slru_read: None,
            slru_write: None,
            value_is_null: None,
            value_get_datum: None,
            value_get_type: None,
            value_get_typmod: None,
            palloc: None,
            palloc0: None,
            repalloc: None,
            pfree: None,
            memory_context_current: None,
            memory_context_switch_to: None,
            memory_context_reset: None,
            memory_context_delete: None,
            ereport: None,
            elog: None,
            error_message: None,
            error_code: None,
            error_clear: None,
            relation_open: None,
            relation_close: None,
            relation_id: None,
            relation_name: None,
            relation_namespace: None,
            relation_tupledesc: None,
            syscache_get_oid: None,
            syscache_get_tuple: None,
            syscache_free_tuple: None,
            planner_info: None,
            free_planner_info: None,
            planner_estimate_rows: None,
            planner_estimate_cost: None,
            transaction_start: None,
            transaction_commit: None,
            transaction_abort: None,
            transaction_is_active: None,
            transaction_get_current_xid: None,
            shmem_alloc: None,
            shmem_free: None,
            shmem_get: None,
            lock_acquire: None,
            lock_release: None,
            lock_held_by_me: None,
            spin_acquire: None,
            spin_release: None,
            autovacuum_is_running: None,
            autovacuum_naptime: None,
            syslogger_log: None,
            walsender_send: None,
            walsender_receive: None,
            walsender_is_connected: None,
            defrem_create: None,
            defrem_alter: None,
            defrem_drop: None,
            node_type: None,
            node_type_name: None,
            node_get_list: None,
            node_list_length: None,
            node_list_get: None,
            query_command_type: None,
            query_rtable: None,
            query_target_list: None,
            query_returning_list: None,
            query_jointree: None,
            query_group_clause: None,
            query_sort_clause: None,
            query_limit_offset: None,
            query_limit_count: None,
            query_has_for_update: None,
            query_has_row_security: None,
            planned_stmt_plan_tree: None,
            planned_stmt_rtable: None,
            planned_stmt_result_relations: None,
            planned_stmt_has_returning: None,
            planned_stmt_has_modifying_cte: None,
            planned_stmt_is_utility: None,
            tuple_natts: None,
            tuple_typeid: None,
            tuple_typmod: None,
            tuple_attname: None,
            tuple_attisdropped: None,
            tuple_attnum: None,
            heap_tuple_getattr: None,
            heap_tuple_setattr: None,
            heap_tuple_tableoid: None,
            heap_tuple_tid: None,
            slot_isnull: None,
            slot_getattr: None,
            slot_tupledesc: None,
            table_am_get: None,
            table_am_beginscan: None,
            table_am_endscan: None,
            table_am_getnext: None,
            table_am_insert: None,
            table_am_update: None,
            table_am_delete: None,
            executor_start: None,
            executor_run: None,
            executor_finish: None,
            executor_end: None,
            executor_getnext: None,
            buffer_get: None,
            buffer_release: None,
            buffer_get_page: None,
            buffer_mark_dirty: None,
            lwlock_acquire: None,
            lwlock_release: None,
            lwlock_held_by_me: None,
            lwlock_cond_acquire: None,
            spinlock_acquire: None,
            spinlock_release: None,
            spinlock_held_by_me: None,
            guc_get_int: None,
            guc_get_string: None,
            guc_get_bool: None,
            guc_get_float: None,
            guc_set_int: None,
            guc_set_string: None,
            guc_set_bool: None,
            guc_set_float: None,
            explain_query: None,
            explain_get_index_name: None,
            vacuum_rel: None,
            vacuum_analyze_rel: None,
            trigger_desc: None,
            trigger_count: None,
            trigger_get: None,
            reorderbuffer_get_lsn: None,
            reorderbuffer_get_xid: None,
            reorderbuffer_get_changes: None,
            slot_get_lsn: None,
            slot_get_catalog_xmin: None,
            slot_is_active: None,
            postmaster_is_alive: None,
            postmaster_get_child_pid: None,
            itempointer_get_block_number: None,
            itempointer_get_offset_number: None,
            itempointer_is_valid: None,
            rel_id: None,
            rel_name: None,
            rel_namespace: None,
            rel_relkind: None,
            rel_relam: None,
            rel_tupledesc: None,
            rel_index_list: None,
            stringinfo_init: None,
            stringinfo_reset: None,
            stringinfo_append: None,
            stringinfo_append_char: None,
            stringinfo_append_int: None,
            stringinfo_data: None,
            stringinfo_len: None,
            memory_chunk_context: None,
            current_memory_context: None,
            raise_error: None,
            try_body: None,
            error_get: None,
            capabilities: None,
            memory_context_create: None,
        }
    }
}
